### ISSUE TITLE
Issue installing on Focal

### ISSUE THREAD

**Issue by opencloudes** [juju-solutions/layer-filebeat#82]
2020-06-30 06:42:45 DEBUG juju.worker.uniter.runner runner.go:701 starting jujuc server  {unix @/var/lib/juju/agents/unit-filebeat-0/agent.socket <nil>}
2020-06-30 06:42:45 DEBUG install Traceback (most recent call last):
2020-06-30 06:42:45 DEBUG install   File "/var/lib/juju/agents/unit-filebeat-0/charm/hooks/install", line 8, in <module>
2020-06-30 06:42:45 DEBUG install     basic.bootstrap_charm_deps()
2020-06-30 06:42:45 DEBUG install   File "lib/charms/layer/basic.py", line 49, in bootstrap_charm_deps
2020-06-30 06:42:45 DEBUG install     activate_venv()
2020-06-30 06:42:45 DEBUG install   File "lib/charms/layer/basic.py", line 205, in activate_venv
2020-06-30 06:42:45 DEBUG install     layer.import_layer_libs()
2020-06-30 06:42:45 DEBUG install   File "lib/charms/layer/__init__.py", line 24, in import_layer_libs
2020-06-30 06:42:45 DEBUG install     import_module('charms.layer.{}'.format(module_name))
2020-06-30 06:42:45 DEBUG install   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-06-30 06:42:45 DEBUG install     return _bootstrap._gcd_import(name[level:], package, level)
2020-06-30 06:42:45 DEBUG install   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-06-30 06:42:45 DEBUG install   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-06-30 06:42:45 DEBUG install   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2020-06-30 06:42:45 DEBUG install   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2020-06-30 06:42:45 DEBUG install   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2020-06-30 06:42:45 DEBUG install   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-06-30 06:42:45 DEBUG install   File "lib/charms/layer/logrotate.py", line 2, in <module>
2020-06-30 06:42:45 DEBUG install     from charmhelpers.core.templating import render
2020-06-30 06:42:45 DEBUG install   File "/var/lib/juju/agents/unit-filebeat-0/.venv/lib/python3.8/site-packages/charmhelpers/core/templating.py", line 18, in <module>
2020-06-30 06:42:45 DEBUG install     from charmhelpers.core import host
2020-06-30 06:42:45 DEBUG install   File "/var/lib/juju/agents/unit-filebeat-0/.venv/lib/python3.8/site-packages/charmhelpers/core/host.py", line 41, in <module>
2020-06-30 06:42:45 DEBUG install     __platform__ = get_platform()
2020-06-30 06:42:45 DEBUG install   File "/var/lib/juju/agents/unit-filebeat-0/.venv/lib/python3.8/site-packages/charmhelpers/osplatform.py", line 13, in get_platform
2020-06-30 06:42:45 DEBUG install     tuple_platform = platform.linux_distribution()
2020-06-30 06:42:45 DEBUG install AttributeError: module 'platform' has no attribute 'linux_distribution'
2020-06-30 06:42:45 ERROR juju.worker.uniter.operation runhook.go:136 hook "install" (via explicit, bespoke hook script) failed: exit status 1

**Comment by ed1000** [comment]
This bug has been fixed: https://github.com/juju/charm-helpers/pull/423
